config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "pages#home"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [ :show, :create, :edit, :update , :destroy ]
  resources :trips, only: [ :index, :show, :new, :create ] do
    resources :trip_activities, only: [ :new, :create ] #:index
    resources :bookings, only: [ :new, :create, :index, :show ]
    resources :tasks, only: [ :new, :create, :index ]
    resources :activities, only: [:index, :show]
  end
  resources :tasks, only: [ :show, :update, :destroy ]

  resources :activities, only: [ :new, :create ]

  # Special routes for notifs stuff
  get "/check_for_notif", to: "notifications#check_for_notif"
  get "/hide_notif_empty_activities", to: "notifications#hide_notif_empty_activities"
  get "/hide_notif_new_booking", to: "notifications#hide_notif_new_booking"
end

app/models/trip_activity.rb
class TripActivity < ApplicationRecord
  belongs_to :trip
  belongs_to :activity

  scope :today_activities, -> { where(date: Date.current) }
  scope :tomorrow_activities, -> { where(date: Date.tomorrow) }

  scope :day_activities, ->(day_date) { where("date = ?", day_date) }
end

app/controllers/trip_activities_controller.rb
class TripActivitiesController < ApplicationController
  before_action :set_trip, only: [:show, :new, :create]

  def show
  end

  def new

    @planned_at = params[:planned_at]
    @booking = @trip.bookings.find_by('begin_date <= :planned_at AND end_date >= :planned_at AND category = :category', planned_at: params[:planned_at], category: 'Hotel') || @trip.bookings.find_by(category: 'Hotel')
    @localisation = @booking&.address

    @tripActivity = TripActivity.new
    # @tripActivity.trip = @trip
     # <---- A mettre ?
    # ON DECIDE DE PÉTÉ SI Y A PAS DE RESERVATION CE JOUR LÀ
    @activities = Activity.near(@localisation, 15).where.not(id: @trip.activities.ids)

    @markers = @activities.geocoded.map do |activity|

        {
          id: activity.id,
          lat: activity.latitude,
          lng: activity.longitude,
          infoWindow: render_to_string(partial: "activities/activity_info_window", locals: { activity: activity }),
          image_url: helpers.asset_url('lucette-marker.svg')
        }

    end
  end

  def create

    # @tripActivity = TripActivity.create(activity_id: @activity ,trip_id: @trip, start_hour: ,date: )
    @tripActivity = TripActivity.new(trip_activity_params)
    @tripActivity.trip = @trip
    if @tripActivity.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  private

  # def not_done(activities, trip)
  #   trip_activities = TripActivity.where(trip_id: trip)
  #   result = []
  #   trip_activities.each do |trip_activity|
  #     activities.each do |activity|
  #       if trip_activity.activity.id != activity.id
  #         result << activity
  #       end
  #     end
  #   result
  #   end
  # end

  def trip_activity_params
    params.require(:trip_activity).permit(:date, :start_hour, :activity_id, :trip_id)
  end

  def set_trip
    @trip = Trip.find(params[:trip_id])
  end
end

app/helpers/trip_activities_helper.rb
module TripActivitiesHelper
    def show_start_hour(start_hour)
        ssh = "#{start_hour.to_time.strftime("%H:%M")}"
        ssh
    end
  end
  

app/views/trip_activities/new.html.erb
<!-- START Tinder like -->
<div class="wrapper-container-tinder h-96 overflow-hidden mx-auto pt-8" id="tinder-list">
  <div class="wrapper-main">
    <div class="font-bold text-md text-center text-white mb-1">
      Activities near my trip
    </div>
    <div class="profiles">
      <% @activities.each do |activity| %>
        <div class="profile" data-activity-id="<%= activity.id %>">
          <%= image_tag "#{activity.photo_title}.jpg", alt: "#{activity.name}", class: "profile-image rounded-xl" %>
          <div class="profile-infos">
            <div class="profile-name">
              <%= activity.name %>
            </div>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>
<!-- END Tinder like -->

<div id="tinderForm" class="hidden absolute w-72 text-center left-11 border-2 rounded-xl">
  <%= simple_form_for [@trip, @tripActivity], url: trip_trip_activities_path(@trip,@tripActivity) do |f| %>
    <%= f.input :date,
                item_wrapper_tag: 'div',
                # item_wrapper_html: { class: "text-white" },
                label: "When do you want to do this?",
                # label_html: { class: 'text-white' },
                required: true,
                input_html: { value: @planned_at,
                              class: "m-2 pl-4 pr-1 py-2 border-gray-300 focus:outline-none sm:text-sm rounded-md" },
                              html5: true %>
    <%= f.input :start_hour,
                as: :select,
                required: true,
                label: "What time?",
                collection: (6..20).map {|n| ["#{n}:00","#{n}:30"]}.flatten,
                wrapper_html: { class: 'flex flex-col items-center justify-center mx-auto w-32' },
                input_html: { type: :date,
                              class: 'm-2 pl-4 pr-1 py-2 border-gray-300 focus:outline-none sm:text-sm rounded-md mx-auto' }%>

    <%#= f.input :trip_id, as: :hidden, value: @current_trip%>
    <%= f.input :activity_id, as: :hidden, value: nil %>
    <%= f.submit value: "Add activity", class: "text-gray-200 text-md font-bold my-3 bg-transparent", data: { disable_with: false } %>
  <% end %>
</div>

<div class="wrapper-container mt-4" id="map"
  style="width: 100%; height: 210px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>