config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "pages#home"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [ :show, :create, :edit, :update , :destroy ]
  resources :trips, only: [ :index, :show, :new, :create ] do
    resources :trip_activities, only: [ :new, :create ] #:index
    resources :bookings, only: [ :new, :create, :index, :show ]
    resources :tasks, only: [ :new, :create, :index ]
    resources :activities, only: [:index, :show]
  end
  resources :tasks, only: [ :show, :update, :destroy ]

  resources :activities, only: [ :new, :create ]

  # Special routes for notifs stuff
  get "/check_for_notif", to: "notifications#check_for_notif"
  get "/hide_notif_empty_activities", to: "notifications#hide_notif_empty_activities"
  get "/hide_notif_new_booking", to: "notifications#hide_notif_new_booking"
end

app/views/shared/_footer.html.erb
<footer id="footer" class="w-screen sticky bottom-0 z-10 shadow-custom-navbar mt-1">
  <div class="flex justify-around pt-2 pb-2">
    <% if @trip && @trip.id %>
      <%= link_to trip_path(@trip) do %>
          <!-- <i class="fas fa-home text-gray-200 text-2xl"></i> -->
        <!-- %img{:src => "/images/image1.svg"} -->
        <%= image_tag "logo-icon.png", alt: "alttext", class: "h-6 mt-1" %>
      <% end %>

      <%= link_to trip_tasks_path(@trip) do %>
        <i class="fas fa-tasks text-gray-200 text-2xl"></i>
      <% end %>
    <% else %>
      <%= link_to new_trip_path() do %>
        <i class="fas fa-home text-gray-200 text-2xl"></i>
      <% end %>
    <% end %>
    <%= link_to user_session_path do %>
      <% if current_user %>
        <i class="fas fa-user text-gray-200 text-2xl"></i>
      <% else %>
        <i class="far fa-user text-gray-200 text-2xl"></i>
      <% end %>
    <% end %>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<% if current_user %>
  <% hide_notif_empty_activities = $hide_notif_empty_activities || false %>
  <% hide_notif_new_booking = $hide_notif_new_booking || false %>
<% else %>
  <% hide_notif_empty_activities = false %>
  <% hide_notif_new_booking = false %>
<% end %>

<nav class="w-screen container justify-between sticky top-0 z-10">
  <ul>
    <li>
      <div class="padding-bell pl-3 pt-2 pb-2 shadow-custom-navbar">
        <%= link_to "#", id: "notifBell" do %>
          <div data-controller="fakenotif" data-fakenotif-target="count">
            <div id="notif-ea-checked" hidden><%= hide_notif_empty_activities %></div>
            <div id="notif-nb-checked" hidden><%= hide_notif_new_booking %></div>
            <i class="far fa-bell text-gray-200 text-2xl text-left"></i>
          </div>
        <% end %>
      </div>
    </li>
    <li>
      <!-- Start Burger menu -->
      <div class="burger-toggle">   <!-- Button to toggle -->
        <div class="burger-toggle-bar"></div>
      </div>
      <!-- Inside Burger -->
      <div class="flex items-center justify-center burger mb-1" id="burger"> <!-- Contenu -->
        <ul>

          <div class="text-burger-custom text-center mx-4 mb-6">
            <li>My trips</li>
          </div>

          <li>
            <% Trip.all.each do |trip| %>
              <div class="wrapper-card-burger relative shadow-custom-card text-center mx-4">
                <%= link_to trip_path(trip) do %>
                    <% if trip.photo_title && !trip.photo_title.empty? %>
                      <%= image_tag "#{trip.photo_title}.jpg", alt: "#{trip.name}", class: "rounded-lg" %>
                    <% end %>
                    <div class="box-content container absolute top-3 content-between">
                      <div class="text-white">
                        <h5><%= trip.name.upcase %></h5>
                      </div>
                      <div>
                        <p>From <%= trip.begin_date %> to <%= trip.end_date %></p>
                      </div>
                    </div>
                <% end %>
              </div>

              <hr>

            <% end %>
          </li>
          <li>
            <div class="container justify-around">
              <div class="text-burger-custom text-center text-sm mx-4">
              Add a trip
              <%= link_to new_trip_path do  %>
                <div class="custom-text-button px-4 py-4">
                  +
                </div>
              <% end %>
            </div>
            </div>
          </li>
        </ul>
      </div>
    </li>




  </ul>
      <!-- End Burger menu -->
</nav>
<div class="hidden body-black-toggle"></div>